openapi: 3.0.3
info:
  title: My E-commerce Store API
  version: 0.0.1
  description: A simple Api
  contact:
    name: APi support
    email: mahdimamashli1383@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
paths: {}
